# Generated by Django 5.2.6 on 2025-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_movie_actors_alter_movie_genres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="db_movie_title_5d0841_idx"),
        ),
    ]
